apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app
  labels:
    app: Streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Streamlit
  template:
    metadata:
      labels:
        app: Streamlit
    spec:
      containers:
        - name: streamlit-container
          image: streamlit-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8501
          envFrom:
            - secretRef:
                name: llmops-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  type: LoadBalancer
  selector:
    app: Streamlit
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501